/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Class.GiaThamChieu;
import Frame.FrMain;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHT
 */
public class PanelSGD extends javax.swing.JPanel {

    /**
     * Creates new form PanelGiaCP
     */
    public PanelSGD() {
        initComponents();
        layDataSGD();
    }

    public void layDataSGD() {

        DefaultTableModel dtm = (DefaultTableModel) jTableSGD.getModel();
        dtm.setNumRows(0);
       
        Vector vt;
        String sql = "select * from SanGiaoDich";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                vt = new Vector();
                vt.add(rs.getString("MaSan"));
                vt.add(rs.getString("TenSan"));
                vt.add(rs.getString("BienDoGia"));
                vt.add(rs.getString("BuocGiaDatLenh"));
                vt.add(rs.getString("LoLechToiThieu"));
              

//                Locale localeVN = new Locale("vi", "VN");
//                NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
//                String str1 = currencyVN.format(tknh.getGiaTC());
//                vt.add(str1);

                dtm.addRow(vt);
            }
            jTableSGD.setModel(dtm);
            rs.close();
            ps.close();
           
        } catch (SQLException ex) {
            Logger.getLogger(PanelSGD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jTableSGD = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTableSGD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableSGD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãSàn", "TênSàn","BiênĐộGiá","BướcGiáĐặtLệnh","LôLệchTốiThiếu"
            }
        ));
        jTableSGD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableSGD.setFillsViewportHeight(true);
        jTableSGD.setFocusable(false);
        jTableSGD.setRowHeight(30);
        jTableSGD.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableSGD.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableSGD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSGDMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableSGD);
        jTableSGD.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableSGD.getTableHeader().setOpaque(false);
        jTableSGD.getTableHeader().setBackground(Color.BLUE);
        jTableSGD.getTableHeader().setForeground(new Color(0,0,0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SÀN GIAO DỊCH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSGDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSGDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableSGDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane9;
    private static javax.swing.JTable jTableSGD;
    // End of variables declaration//GEN-END:variables
}
