/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Class.GiaThamChieu;
import Frame.FrMain;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHT
 */
public class PanelLSGia extends javax.swing.JPanel {

    /**
     * Creates new form PanelGiaCP
     */
    public PanelLSGia() {
        initComponents();
        layDataLSGia();
    }

    public void layDataLSGia() {

        DefaultTableModel dtm = (DefaultTableModel) jTableLSGia.getModel();
        dtm.setNumRows(0);
       
        Vector vt;
        String sql = "select * from GiaThamChieu";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                GiaThamChieu tknh = new GiaThamChieu(rs.getString("MaCP"), rs.getDate("NgayGD"), rs.getFloat("GiaTC"));

                vt = new Vector();
                vt.add(tknh.getMaCP());
                vt.add(tknh.getNgayGD());

                Locale localeVN = new Locale("vi", "VN");
                NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                String str1 = currencyVN.format(tknh.getGiaTC());
                vt.add(str1);

                dtm.addRow(vt);
            }
            jTableLSGia.setModel(dtm);
            rs.close();
            ps.close();
           
        } catch (SQLException ex) {
            Logger.getLogger(PanelLSGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jTableLSGia = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTableLSGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLSGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãCP", "NgàyGiaoDịch","GiáThamChiếu"
            }
        ));
        jTableLSGia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableLSGia.setFillsViewportHeight(true);
        jTableLSGia.setFocusable(false);
        jTableLSGia.setRowHeight(30);
        jTableLSGia.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableLSGia.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableLSGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLSGiaMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableLSGia);
        jTableLSGia.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableLSGia.getTableHeader().setOpaque(false);
        jTableLSGia.getTableHeader().setBackground(Color.BLUE);
        jTableLSGia.getTableHeader().setForeground(new Color(0,0,0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LỊCH SỬ GIÁ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLSGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLSGiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLSGiaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane9;
    private static javax.swing.JTable jTableLSGia;
    // End of variables declaration//GEN-END:variables
}
