/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Class.LenhDat;
import Frame.FrDNGD;
import Frame.FrMain;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeDate.parse;

/**
 *
 * @author NHT
 */
public class PanelDSLenh extends javax.swing.JPanel {

    /**
     * Creates new form PanelGiaCP
     */
    private LenhDat ld;
    
    public PanelDSLenh() {
        initComponents();
        layDataLenhDat();
    }

  public void layDataLenhDat() {
        DefaultTableModel dtm = (DefaultTableModel) jTableDSLenh.getModel();
        dtm.setNumRows(0);
       
        Vector vt;
        String sql = "select * from LenhDat";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                LenhDat ld = new LenhDat(rs.getString("MaLenh"), rs.getString("MaTKNH"), rs.getString("MaCP"), rs.getString("LoaiGD"), rs.getInt("SLDat"), rs.getTimestamp("NgayGioDat"), rs.getString("MaLoaiLenh"), rs.getString("MaTrangThai"), rs.getFloat("GiaDat"));

                vt = new Vector();
                vt.add(ld.getMaLenh());
                vt.add(ld.getMaTKNH());
                vt.add(ld.getMaCP());
                vt.add(ld.getLoaiGD());
                vt.add(ld.getSlDat());

                Locale localeVN = new Locale("vi", "VN");
                NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                String str1 = currencyVN.format(ld.getGiaDat());
                vt.add(str1);

                vt.add(ld.getNgayGioDat());
                vt.add(ld.getMaLoaiLenh());
                vt.add(ld.getMaTrangThai());

                dtm.addRow(vt);
            }
            jTableDSLenh.setModel(dtm);
            rs.close();
            ps.close();
           
        } catch (SQLException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEdit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonHuyLenh = new javax.swing.JButton();
        jButtonBackCP2 = new javax.swing.JButton();
        jButtonDatLenh = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableDSLenh = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));

        jButtonEdit.setText("Sửa Lệnh");
        jButtonEdit.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DANH SÁCH LỆNH");

        jButtonHuyLenh.setText("Huỷ Lệnh");
        jButtonHuyLenh.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonHuyLenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyLenhActionPerformed(evt);
            }
        });

        jButtonBackCP2.setText("Back");

        jButtonDatLenh.setText("Đặt Lệnh");
        jButtonDatLenh.setPreferredSize(new java.awt.Dimension(110, 25));
        jButtonDatLenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatLenhActionPerformed(evt);
            }
        });

        jTableDSLenh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableDSLenh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãLệnh", "MãTKNH","MãCP","LoạiGD","SLĐặt","GiáĐặt","NgàyGiờĐặt","MãLoạiLệnh","TrạngThái"
            }
        ));
        jTableDSLenh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableDSLenh.setFillsViewportHeight(true);
        jTableDSLenh.setFocusable(false);
        jTableDSLenh.setRowHeight(30);
        jTableDSLenh.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableDSLenh.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableDSLenh.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableDSLenh.getTableHeader().setReorderingAllowed(false);
        jTableDSLenh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDSLenhMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTableDSLenh);
        jTableDSLenh.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableDSLenh.getTableHeader().setOpaque(false);
        jTableDSLenh.getTableHeader().setBackground(Color.BLUE);
        jTableDSLenh.getTableHeader().setForeground(new Color(0,0,0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(jButtonDatLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHuyLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBackCP2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(578, 578, 578))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDatLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHuyLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBackCP2))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHuyLenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyLenhActionPerformed
        // TODO add your handling code here:
        if(ld==null)
        {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Lệnh");
            return;
        }
        else if("KH".equals(ld.getMaTrangThai()) || "CAK".equals(ld.getMaTrangThai()))
        {
              JOptionPane.showMessageDialog(this, "Lệnh Này Không Đc Sửa");
            return;
        }
        new FrDNGD(ld,3).setVisible(true);
    }//GEN-LAST:event_jButtonHuyLenhActionPerformed

    private void jTableDSLenhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDSLenhMouseClicked
        // TODO add your handling code here:
        ld=new LenhDat();
        DefaultTableModel dtm = (DefaultTableModel) jTableDSLenh.getModel();
        ld.setMaLenh(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 0).toString());
        ld.setMaTKNH(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 1).toString());
        ld.setMaCP(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 2).toString());
        ld.setLoaiGD(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 3).toString());
        ld.setSlDat(Integer.valueOf(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 4).toString()));
        
        Locale localeVN = new Locale("vi", "VN");
        float floatNumber = (float) parse(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 5), localeVN);
        ld.setGiaDat(floatNumber);
        
        ld.setNgayGioDat(Timestamp.valueOf(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 6).toString()));
        ld.setMaLoaiLenh(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 7).toString());
        ld.setMaTrangThai(dtm.getValueAt(jTableDSLenh.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_jTableDSLenhMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if(ld==null)
        {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Lệnh");
            return;
        }
        else if("KH".equals(ld.getMaTrangThai()) || "CHK".equals(ld.getMaTrangThai()))
        {
              JOptionPane.showMessageDialog(this, "Lệnh Này Không Đc Sửa");
            return;
        }
        System.out.println("asds " + ld.getMaTKNH());
        new FrDNGD(ld,2).setVisible(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDatLenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatLenhActionPerformed
        // TODO add your handling code here:
        new FrDNGD().setVisible(true);
 
    }//GEN-LAST:event_jButtonDatLenhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCP2;
    private javax.swing.JButton jButtonDatLenh;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHuyLenh;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable jTableDSLenh;
    // End of variables declaration//GEN-END:variables
}
