/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Frame.FrMain;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHT
 */
public class PanelTT extends javax.swing.JPanel {

    /**
     * Creates new form PanelGiaCP
     */
    public PanelTT() {
        initComponents();
        layDataTrangThai();
    }
    
     public void layDataTrangThai() {
        DefaultTableModel dtm = (DefaultTableModel) jTableTT.getModel();
        dtm.setNumRows(0);
       
        Vector vt;
        String sql = "select * from TrangThai";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                vt=new Vector();
                vt.add(rs.getString("MaTrangThai"));
                vt.add(rs.getString("DienGiai"));
                vt.add(rs.getString("TenTrangThai"));

                dtm.addRow(vt);
            }
            jTableTT.setModel(dtm);
            rs.close();
            ps.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jTableTT = new javax.swing.JTable();
        jButtonBackCP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTableTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãLệnh", "TênLệnh","MôTả"
            }
        ));
        jTableTT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableTT.setFillsViewportHeight(true);
        jTableTT.setFocusable(false);
        jTableTT.setRowHeight(30);
        jTableTT.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableTT.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTTMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableTT);
        jTableTT.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableTT.getTableHeader().setOpaque(false);
        jTableTT.getTableHeader().setBackground(Color.BLUE);
        jTableTT.getTableHeader().setForeground(new Color(0,0,0));

        jButtonBackCP.setText("Back");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TRẠNG THÁI LỆNH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(580, 580, 580))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBackCP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(705, 705, 705))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonBackCP)
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableTTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCP;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableTT;
    // End of variables declaration//GEN-END:variables
}
