/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Frame.FrAddNDT;
import Class.KetNoiSQL;
import Class.NhaDauTu;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHT
 */
public class PanelNDT extends javax.swing.JPanel {

    /**
     * Creates new form PanelNDT
     */
    private String maTK;

    public PanelNDT() {
        initComponents();
        layDataNDT();
    }
    
    public void layDataNDT() {

        DefaultTableModel dtm = (DefaultTableModel) jTableNDT.getModel();
        dtm.setNumRows(0);

        String sql = "select * from NhaDauTu";
        Vector vt;
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {

                vt = new Vector();
                vt.add(rs.getString("MaTK"));
                vt.add(rs.getString("Ho") + " " + rs.getString("Ten"));
                vt.add(rs.getString("NgaySinh"));
                vt.add(rs.getString("NoiSinh"));
                vt.add(rs.getString("Phai"));
                vt.add(rs.getString("DiaChi"));
                vt.add(rs.getString("Email"));
                vt.add(rs.getString("SDT"));
                vt.add(rs.getString("CMND"));
                vt.add(rs.getString("NgayCap"));
                vt.add(rs.getString("NoiCap"));
                vt.add(rs.getString("TrNgNc"));
                dtm.addRow(vt);
            }
            jTableNDT.setModel(dtm);
            rs.close();
            ps.close();
           
        } catch (SQLException ex) {
            Logger.getLogger(PanelNDT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      
    public void xoaNDT(String maTK) {
       
        String sql = "delete from NhaDauTu where MaTK = ?";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, maTK);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(PanelNDT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNDT = new javax.swing.JTable();
        lbtb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDel.setText("Delete");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DANH SÁCH NHÀ ĐẦU TƯ");

        jTableNDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableNDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "MãTK", "Họ Tên", "NgàySinh", "NơiSinh", "Phái", "ĐịaChỉ", "Email", "SDT", "CMND/HộChiếu", "NgàyCấp", "NơiCấp", "TrongNgoàiNước"
            }
        ));
        jTableNDT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableNDT.setFocusable(false);
        jTableNDT.setGridColor(new java.awt.Color(153, 153, 153));
        jTableNDT.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableNDT.setRowHeight(30);
        jTableNDT.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableNDT.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableNDT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableNDT.setShowVerticalLines(false);
        jTableNDT.getTableHeader().setReorderingAllowed(false);
        jTableNDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNDTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNDT);
        jTableNDT.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableNDT.getTableHeader().setOpaque(false);
        jTableNDT.getTableHeader().setBackground(Color.red);
        jTableNDT.getTableHeader().setForeground(new Color(0,0,0));

        lbtb.setBackground(new java.awt.Color(0, 0, 0));
        lbtb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtb.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(543, 543, 543)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbtb)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 531, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1476, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbtb)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDel)
                    .addComponent(jButtonBack))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableNDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNDTMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTableNDT.getModel();
        maTK = dtm.getValueAt(jTableNDT.getSelectedRow(), 0).toString();
    }//GEN-LAST:event_jTableNDTMouseClicked

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        new FrAddNDT().setVisible(true);
        //lbtb.setText("Thêm thành công");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if (maTK == null) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Nhà Đầu Tư");
            return;
        }
        NhaDauTu ndt = null;
        Connection ketNoi = KetNoiSQL.layKetNoi();
        String sql = "select * from NhaDauTu where MaTK ='" + maTK + "'";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                ndt = new NhaDauTu(rs.getString("MaTK"), rs.getString("Ho"), rs.getString("Ten"), rs.getDate("NgaySinh"), rs.getString("NoiSinh"), rs.getString("Phai"), rs.getString("DiaChi"), rs.getString("Email"), rs.getString("SDT"), rs.getString("CMND"), rs.getDate("NgayCap"), rs.getString("NoiCap"), rs.getString("TrNgNc"), rs.getString("MMGD"), rs.getString("MKDL"));
            }
            rs.close();
            ps.close();
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(PanelNDT.class.getName()).log(Level.SEVERE, null, ex);
        }

        new FrAddNDT(ndt).setVisible(true);
        layDataNDT();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        if (maTK == null) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn Nhà Đầu Tư");
        }
        int ret = JOptionPane.showConfirmDialog(this, "Ban chac chan muon xoa?", "Xac nhan", 0);
        if (ret == JOptionPane.CANCEL_OPTION) {

        } else if (ret == JOptionPane.OK_OPTION) {
            xoaNDT(maTK);
            JOptionPane.showMessageDialog(this, "Xóa sách thành công");
            layDataNDT();
        }
        maTK = null;
    }//GEN-LAST:event_jButtonDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNDT;
    private javax.swing.JLabel lbtb;
    // End of variables declaration//GEN-END:variables
}
