/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Frame.FrMain;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NHT
 */
public class PanelGiaCP extends javax.swing.JPanel {

    /**
     * Creates new form PanelGiaCP
     */
    public PanelGiaCP() {
        initComponents();
        //layDataLSGia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jTableGiaCP = new javax.swing.JTable();
        jButtonBackCP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTableGiaCP.setBackground(new java.awt.Color(204, 204, 204));
        jTableGiaCP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableGiaCP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãCP", "NgàyGiaoDịch","GiáThamChiếu","GiaSàn","GiáTrần"
            }
        ));
        DefaultTableCellRenderer rendar1 = new DefaultTableCellRenderer();
        rendar1.setForeground(Color.YELLOW);

        jTableGiaCP.getColumnModel().getColumn(2).setCellRenderer(rendar1);
        jTableGiaCP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableGiaCP.setFillsViewportHeight(true);
        jTableGiaCP.setFocusable(false);
        jTableGiaCP.setRowHeight(30);
        jTableGiaCP.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableGiaCP.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableGiaCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGiaCPMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableGiaCP);
        jTableGiaCP.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableGiaCP.getTableHeader().setOpaque(false);
        jTableGiaCP.getTableHeader().setBackground(Color.BLUE);
        jTableGiaCP.getTableHeader().setForeground(new Color(0,0,0));

        jButtonBackCP.setText("Back");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BẢNG GIÁ CỐ PHIẾU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(695, 695, 695)
                        .addComponent(jButtonBackCP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonBackCP)
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableGiaCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGiaCPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableGiaCPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCP;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableGiaCP;
    // End of variables declaration//GEN-END:variables
}
