/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Class.LuuKy;
import Frame.FrMain;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHT
 */
public class PanelLK extends javax.swing.JPanel {

    /**
     * Creates new form PanelLK
     */
    public PanelLK() {
        initComponents();
        layDataLK();
    }

    public void layDataLK() {

        DefaultTableModel dtm = (DefaultTableModel) jTableLuuKy.getModel();
        dtm.setNumRows(0);

       
        Vector vt;
        String sql = "select * from SoHuu";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                LuuKy cp = new LuuKy(rs.getString("MaTK"), rs.getString("MaCP"), rs.getInt("SoLg"));
                vt = new Vector();
                vt.add(cp.getMaTK());
                vt.add(cp.getMaCP());
                vt.add(cp.getSoLg());
                dtm.addRow(vt);
            }
            jTableLuuKy.setModel(dtm);
            rs.close();
            ps.close();
           
        } catch (SQLException ex) {
            Logger.getLogger(PanelLK.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTableLuuKy = new javax.swing.JTable();
        jButtonBackTKNN1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTableLuuKy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLuuKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãTK", "MãCP","SốLượng"
            }
        ));
        jTableLuuKy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableLuuKy.setFillsViewportHeight(true);
        jTableLuuKy.setRowHeight(30);
        jTableLuuKy.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableLuuKy.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableLuuKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLuuKyMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTableLuuKy);
        jTableLuuKy.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableLuuKy.getTableHeader().setOpaque(false);
        jTableLuuKy.getTableHeader().setBackground(Color.BLUE);
        jTableLuuKy.getTableHeader().setForeground(new Color(0,0,0));

        jButtonBackTKNN1.setText("Back");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LƯU KÝ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonBackTKNN1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(698, 698, 698))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(675, 675, 675))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonBackTKNN1)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLuuKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLuuKyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLuuKyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackTKNN1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableLuuKy;
    // End of variables declaration//GEN-END:variables
}
