/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Class.LenhKhop;
import Frame.FrMain;
import static Frame.FrMain.ketNoi;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NHT
 */
public class PanelLenhKhop extends javax.swing.JPanel {

    /**
     * Creates new form PanelGiaCP
     */
    public PanelLenhKhop() {
        initComponents();
        layDataLenhKhop();
    }

   public void layDataLenhKhop() {
        DefaultTableModel dtm = (DefaultTableModel) jTableLenhKhop.getModel();
        dtm.setNumRows(0);
       
        Vector vt;
        String sql = "select * from LenhKhop";
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                LenhKhop lk = new LenhKhop(rs.getString("MaLenh"), rs.getTimestamp("NgayGioKhop"), rs.getFloat("GiaKhop"), rs.getInt("SoLgKhop"));

                vt = new Vector();
                vt.add(lk.getMaLenh());
                vt.add(lk.getNgayGioKhop());

                Locale localeVN = new Locale("vi", "VN");
                NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                String str1 = currencyVN.format(lk.getGiaKhop());
                vt.add(str1);

                vt.add(lk.getSoLgKhop());
                dtm.addRow(vt);
            }
            jTableLenhKhop.setModel(dtm);
            rs.close();
            ps.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(PanelLenhKhop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jTableLenhKhop = new javax.swing.JTable();
        jButtonBackCP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jTableLenhKhop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLenhKhop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MãLệnh", "NgàyGiờKhớp","GiáKhớp","SốLgKhớp"
            }
        ));
        jTableLenhKhop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableLenhKhop.setFillsViewportHeight(true);
        jTableLenhKhop.setFocusable(false);
        jTableLenhKhop.setRowHeight(30);
        jTableLenhKhop.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jTableLenhKhop.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableLenhKhop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLenhKhopMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jTableLenhKhop);
        jTableLenhKhop.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        jTableLenhKhop.getTableHeader().setOpaque(false);
        jTableLenhKhop.getTableHeader().setBackground(Color.BLUE);
        jTableLenhKhop.getTableHeader().setForeground(new Color(0,0,0));

        jButtonBackCP.setText("Back");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LỆNH KHỚP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(661, 661, 661)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(726, 726, 726)
                        .addComponent(jButtonBackCP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonBackCP)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableLenhKhopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLenhKhopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableLenhKhopMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCP;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableLenhKhop;
    // End of variables declaration//GEN-END:variables
}
