/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Scanner;
import javax.swing.JOptionPane;
import Class.KetNoiSQL;
import Class.ThucHienGD;
import Class.RunnableUpdate;
import Panel.PanelDSLenh;
import Panel.PanelNDT;
import Panel.PanelLK;
import Panel.PanelLL;
import Panel.PanelLSGia;
import Panel.PanelLenhKhop;
import Panel.PanelTKNH;
import Panel.PanelTT;
import Panel.PanelTTCP;
import Panel.PanelGiaCP;
import Panel.PanelSGD;
import Panel.PanelThongKe;
import Panel.PanelTinTuc;
/**
 *
 * @author NHT
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    private String maTK;
    private String maTKNH;
    public static int maGD[];
    public static int soLgMaGD;
    public static Connection ketNoi = KetNoiSQL.layKetNoi();
    private RunnableUpdate r1=null;
    
    public FrMain() {
        initComponents();
        ketNoi = KetNoiSQL.layKetNoi();
        try {
            docMaGD();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        new ThucHienGD().update();
       
        r1=new RunnableUpdate("Start");
        r1.start();
        
        jPanelMain.removeAll();
        jPanelMain.add(jPanelTrangChu);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        jPanelMTC.add(new PanelTinTuc());
        jPanelMTC.repaint();
        jPanelMTC.revalidate();
    }
    
    public void docMaGD() throws FileNotFoundException{
        soLgMaGD=0;
        maGD=new int[10000];
        Scanner s = null;
        try {
            s = new Scanner(new BufferedReader(new FileReader("MaGD.txt")));
            while (s.hasNext()) {
               maGD[soLgMaGD++]=s.nextInt();
             //   System.out.println(maGD[soLgMaGD-1]);
            }
        } finally {
            if (s != null) {
                s.close();
            }
        }
    }
    
    public void writeFile() {
        // Create new Countrys objects
        // Create a new list of Country objects
        FileWriter fileWriter = null;

        try {
            fileWriter = new FileWriter("MaGD.txt");
            for (int i=0;i<soLgMaGD;i++) {
                fileWriter.append(maGD[i]+" ");
            }

            System.out.println("CSV file was created successfully !!!");

        } catch (Exception e) {
            System.out.println("Error in CsvFileWriter !!!");
            e.printStackTrace();
        } finally {
            try {
                fileWriter.flush();
                fileWriter.close();
            } catch (IOException e) {
                System.out.println("Error while flushing/closing fileWriter !!!");
                e.printStackTrace();
            }
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonQLNDT = new javax.swing.JButton();
        jButtonQLCP = new javax.swing.JButton();
        jButtonQLGD = new javax.swing.JButton();
        jButtonTC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jPanelQLCP = new javax.swing.JPanel();
        jButtonTTCP = new javax.swing.JButton();
        jButtonLSGia = new javax.swing.JButton();
        jButtonSGD = new javax.swing.JButton();
        jButtonThongKe = new javax.swing.JButton();
        jPanelMQLCP = new javax.swing.JPanel();
        jPanelQLGD = new javax.swing.JPanel();
        jButtonDSLenh = new javax.swing.JButton();
        jButtonLoaiLenh = new javax.swing.JButton();
        jButtonTrangThai = new javax.swing.JButton();
        jButtonLenhKhop = new javax.swing.JButton();
        jPanelMQLGD = new javax.swing.JPanel();
        jPanelQLNDT = new javax.swing.JPanel();
        jButtonLK = new javax.swing.JButton();
        jButtonTKNH = new javax.swing.JButton();
        jButtonNDT = new javax.swing.JButton();
        jPanelMQLNDT = new javax.swing.JPanel();
        jPanelTT = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanelTrangChu = new javax.swing.JPanel();
        jPanelMTC = new javax.swing.JPanel();
        jButtonTinTuc = new javax.swing.JButton();
        jButtonHSX = new javax.swing.JButton();
        jButtonHNX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QLGD");
        setMinimumSize(new java.awt.Dimension(1500, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(1500, 146));

        jButtonQLNDT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQLNDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQLNDT.setText("Nhà Đầu Tư");
        jButtonQLNDT.setToolTipText("Quản Lí Nhà Đầu Tư");
        jButtonQLNDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonQLNDTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonQLNDTMouseExited(evt);
            }
        });
        jButtonQLNDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLNDTActionPerformed(evt);
            }
        });

        jButtonQLCP.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQLCP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQLCP.setText("Cổ Phiếu");
        jButtonQLCP.setToolTipText("Quản Lí Cổ Phiếu");
        jButtonQLCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonQLCPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonQLCPMouseExited(evt);
            }
        });
        jButtonQLCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLCPActionPerformed(evt);
            }
        });

        jButtonQLGD.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQLGD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonQLGD.setText("Giao Dịch ");
        jButtonQLGD.setToolTipText("Quản Lí Giao DỊch");
        jButtonQLGD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonQLGDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonQLGDMouseExited(evt);
            }
        });
        jButtonQLGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLGDActionPerformed(evt);
            }
        });

        jButtonTC.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTC.setText("Trang Chủ");
        jButtonTC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonTC.setSelected(true);
        jButtonTC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTCMouseExited(evt);
            }
        });
        jButtonTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTCActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_contacts_64px.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo1.jpg"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jButtonTC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQLNDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQLCP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQLGD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonQLNDT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonQLCP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonQLGD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 120));

        jPanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelMain.setLayout(new java.awt.CardLayout());

        jPanelQLCP.setPreferredSize(new java.awt.Dimension(1500, 700));

        jButtonTTCP.setText("TTCP");
        jButtonTTCP.setToolTipText("Thông TIn Cổ Phiếu");
        jButtonTTCP.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonTTCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTTCPActionPerformed(evt);
            }
        });

        jButtonLSGia.setText("LSGiá");
        jButtonLSGia.setToolTipText("Lịch Sử Giá");
        jButtonLSGia.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonLSGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLSGiaActionPerformed(evt);
            }
        });

        jButtonSGD.setText("SGD");
        jButtonSGD.setToolTipText("Sàn Giao DỊch");
        jButtonSGD.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonSGD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSGDActionPerformed(evt);
            }
        });

        jButtonThongKe.setText("Thống Kê");
        jButtonThongKe.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThongKeActionPerformed(evt);
            }
        });

        jPanelMQLCP.setPreferredSize(new java.awt.Dimension(0, 650));
        jPanelMQLCP.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelQLCPLayout = new javax.swing.GroupLayout(jPanelQLCP);
        jPanelQLCP.setLayout(jPanelQLCPLayout);
        jPanelQLCPLayout.setHorizontalGroup(
            jPanelQLCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLCPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTTCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLSGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1065, Short.MAX_VALUE))
            .addComponent(jPanelMQLCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelQLCPLayout.setVerticalGroup(
            jPanelQLCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLCPLayout.createSequentialGroup()
                .addGroup(jPanelQLCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQLCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelQLCPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTTCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLSGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMQLCP, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelMain.add(jPanelQLCP, "card2");

        jPanelQLGD.setPreferredSize(new java.awt.Dimension(1500, 700));

        jButtonDSLenh.setText("DSLệnh");
        jButtonDSLenh.setToolTipText("Danh Sách Lệnh");
        jButtonDSLenh.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonDSLenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDSLenhActionPerformed(evt);
            }
        });

        jButtonLoaiLenh.setText("Loại Lệnh");
        jButtonLoaiLenh.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonLoaiLenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoaiLenhActionPerformed(evt);
            }
        });

        jButtonTrangThai.setText("Trạng Thái");
        jButtonTrangThai.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrangThaiActionPerformed(evt);
            }
        });

        jButtonLenhKhop.setText("Lệnh Khớp");
        jButtonLenhKhop.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonLenhKhop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLenhKhopActionPerformed(evt);
            }
        });

        jPanelMQLGD.setPreferredSize(new java.awt.Dimension(112, 650));
        jPanelMQLGD.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelQLGDLayout = new javax.swing.GroupLayout(jPanelQLGD);
        jPanelQLGD.setLayout(jPanelQLGDLayout);
        jPanelQLGDLayout.setHorizontalGroup(
            jPanelQLGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLGDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDSLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLoaiLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLenhKhop, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1065, Short.MAX_VALUE))
            .addComponent(jPanelMQLGD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelQLGDLayout.setVerticalGroup(
            jPanelQLGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLGDLayout.createSequentialGroup()
                .addGroup(jPanelQLGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLenhKhop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelQLGDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDSLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLoaiLenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMQLGD, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(jPanelQLGD, "card2");

        jPanelQLNDT.setPreferredSize(new java.awt.Dimension(1500, 650));

        jButtonLK.setText("LưuKý");
        jButtonLK.setToolTipText("");
        jButtonLK.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonLK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLKActionPerformed(evt);
            }
        });

        jButtonTKNH.setText("TKNH");
        jButtonTKNH.setToolTipText("Tài Khoản Ngân Hàng");
        jButtonTKNH.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonTKNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTKNHActionPerformed(evt);
            }
        });

        jButtonNDT.setText("NĐT");
        jButtonNDT.setToolTipText("Nhà Đầu Tư");
        jButtonNDT.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonNDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNDTActionPerformed(evt);
            }
        });

        jPanelMQLNDT.setPreferredSize(new java.awt.Dimension(0, 650));
        jPanelMQLNDT.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelQLNDTLayout = new javax.swing.GroupLayout(jPanelQLNDT);
        jPanelQLNDT.setLayout(jPanelQLNDTLayout);
        jPanelQLNDTLayout.setHorizontalGroup(
            jPanelQLNDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLNDTLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButtonNDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTKNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1177, Short.MAX_VALUE))
            .addComponent(jPanelMQLNDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelQLNDTLayout.setVerticalGroup(
            jPanelQLNDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQLNDTLayout.createSequentialGroup()
                .addGroup(jPanelQLNDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTKNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMQLNDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelMain.add(jPanelQLNDT, "card3");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 650));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fb.png"))); // NOI18N
        jLabel6.setToolTipText("https://www.facebook.com/phucquoc.dong");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("CÔNG TY CHỨNG KHOÁN QTQ");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Địa chỉ trụ sở: 332B Lý Thường Kiệt, Phường 14, Quận 10, Thành phố Hồ Chí Minh");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.jpg"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Người chịu trách nhiệm: Quokka");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Thư điện tử : informationsofbbc@vng.com.vn");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Số điện thoại liên hệ : 0985879703");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("274/GP - BTTTT do Bộ TT & TT");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("cấp ngày 29 /06/2019");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Cơ quan cấp phép: Bộ Thông tin và Truyền thông");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 255, 0));
        jLabel16.setText("Điều khoản");
        jLabel16.setToolTipText("https://www.qtqctck.com/cac-dieu-khoan");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 255, 0));
        jLabel18.setText("Chính sách bảo mật");
        jLabel18.setToolTipText("https://www.qtqctck.com/chinh-sach-bao-mat");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("Phản hồi");
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Trợ giúp");
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(240, 240, 240));
        jLabel36.setText("Zalo truy cập : \"https://chat.zalo.me/?c=\" ");

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(240, 240, 240));
        jLabel37.setText("Twitter truy cập : \"https://twitter.com/login/0985879703\"");

        jLabel38.setToolTipText("Người tham gia hoạt động chính khoán buộc phải có CMND");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yt.jpg"))); // NOI18N
        jLabel39.setToolTipText("https://www.youtube.com/watch?v=_WzpOXS2wlY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(229, 229, 229)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(639, 639, 639))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(615, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(600, 600, 600))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(611, 611, 611))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(559, 559, 559))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(651, 651, 651)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(593, 593, 593)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel39))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelTTLayout = new javax.swing.GroupLayout(jPanelTT);
        jPanelTT.setLayout(jPanelTTLayout);
        jPanelTTLayout.setHorizontalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1498, Short.MAX_VALUE)
        );
        jPanelTTLayout.setVerticalGroup(
            jPanelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTTLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMain.add(jPanelTT, "card2");

        jPanelTrangChu.setPreferredSize(new java.awt.Dimension(1500, 700));

        jPanelMTC.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMTC.setForeground(new java.awt.Color(240, 240, 240));
        jPanelMTC.setLayout(new java.awt.CardLayout());

        jButtonTinTuc.setText("Tin Tức");
        jButtonTinTuc.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonTinTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTinTucActionPerformed(evt);
            }
        });

        jButtonHSX.setText("HSX");
        jButtonHSX.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonHSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHSXActionPerformed(evt);
            }
        });

        jButtonHNX.setText("HNX");
        jButtonHNX.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonHNX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHNXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrangChuLayout = new javax.swing.GroupLayout(jPanelTrangChu);
        jPanelTrangChu.setLayout(jPanelTrangChuLayout);
        jPanelTrangChuLayout.setHorizontalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMTC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTrangChuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButtonTinTuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHNX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTrangChuLayout.setVerticalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuLayout.createSequentialGroup()
                .addGroup(jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTinTuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHNX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelTrangChu, "card2");

        getContentPane().add(jPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1500, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQLCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLCPActionPerformed
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.add(jPanelQLCP);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        jPanelMQLCP.add(new PanelTTCP());
        jPanelMQLCP.repaint();
        jPanelMQLCP.revalidate();
    }//GEN-LAST:event_jButtonQLCPActionPerformed

    private void jButtonQLNDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLNDTActionPerformed
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.add(jPanelQLNDT);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        jPanelMQLNDT.add(new PanelNDT());
        jPanelMQLNDT.repaint();
        jPanelMQLNDT.revalidate();
    }//GEN-LAST:event_jButtonQLNDTActionPerformed

    private void jButtonNDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNDTActionPerformed
        // TODO add your handling code here:
        jPanelMQLNDT.removeAll();
        jPanelMQLNDT.add(new PanelNDT());
        jPanelMQLNDT.repaint();
        jPanelMQLNDT.revalidate();
    }//GEN-LAST:event_jButtonNDTActionPerformed

    private void jButtonTKNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTKNHActionPerformed
        // TODO add your handling code here:
        jPanelMQLNDT.removeAll();
        jPanelMQLNDT.add(new PanelTKNH());
        jPanelMQLNDT.repaint();
        jPanelMQLNDT.revalidate();
    }//GEN-LAST:event_jButtonTKNHActionPerformed

    private void jButtonLKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLKActionPerformed
        // TODO add your handling code here:
        jPanelMQLNDT.removeAll();
        jPanelMQLNDT.add(new PanelLK());
        jPanelMQLNDT.repaint();
        jPanelMQLNDT.revalidate();
    }//GEN-LAST:event_jButtonLKActionPerformed

    private void jButtonQLGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLGDActionPerformed
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.add(jPanelQLGD);
        jPanelMain.repaint();
        jPanelMain.revalidate();
        jPanelMQLGD.add(new PanelDSLenh());
        jPanelMQLGD.repaint();
        jPanelMQLGD.revalidate();
    }//GEN-LAST:event_jButtonQLGDActionPerformed

    private void jButtonLenhKhopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLenhKhopActionPerformed
        // TODO add your handling code here:
        jPanelMQLGD.removeAll();
        jPanelMQLGD.add(new PanelLenhKhop());
        jPanelMQLGD.repaint();
        jPanelMQLGD.revalidate();
    }//GEN-LAST:event_jButtonLenhKhopActionPerformed

    private void jButtonTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrangThaiActionPerformed
        // TODO add your handling code here:
        jPanelMQLGD.removeAll();
        jPanelMQLGD.add(new PanelTT());
        jPanelMQLGD.repaint();
        jPanelMQLGD.revalidate();
    }//GEN-LAST:event_jButtonTrangThaiActionPerformed

    private void jButtonLoaiLenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoaiLenhActionPerformed
        // TODO add your handling code here:
        jPanelMQLGD.removeAll();
        jPanelMQLGD.add(new PanelLL());
        jPanelMQLGD.repaint();
        jPanelMQLGD.revalidate();
    }//GEN-LAST:event_jButtonLoaiLenhActionPerformed

    private void jButtonDSLenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDSLenhActionPerformed
        // TODO add your handling code here:
        jPanelMQLGD.removeAll();
        jPanelMQLGD.add(new PanelDSLenh());
        jPanelMQLGD.repaint();
        jPanelMQLGD.revalidate();
    }//GEN-LAST:event_jButtonDSLenhActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        writeFile();
        try {
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jButtonTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTCActionPerformed
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.add(jPanelTrangChu);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_jButtonTCActionPerformed

    private void jButtonLSGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLSGiaActionPerformed
        // TODO add your handling code here:
        jPanelMQLCP.removeAll();
        jPanelMQLCP.add(new PanelLSGia());
        jPanelMQLCP.repaint();
        jPanelMQLCP.revalidate();
    }//GEN-LAST:event_jButtonLSGiaActionPerformed

    private void jButtonTTCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTTCPActionPerformed
        // TODO add your handling code here:
        jPanelMQLCP.removeAll();
        jPanelMQLCP.add(new PanelTTCP());
        jPanelMQLCP.repaint();
        jPanelMQLCP.revalidate();
    }//GEN-LAST:event_jButtonTTCPActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        r1.stopt();
        writeFile();
        try {
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        new FrDN().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         jLabel3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jButtonSGDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSGDActionPerformed
        // TODO add your handling code here:
        jPanelMQLCP.removeAll();
        jPanelMQLCP.add(new PanelSGD());
        jPanelMQLCP.repaint();
        jPanelMQLCP.revalidate();
    }//GEN-LAST:event_jButtonSGDActionPerformed

    private void jButtonThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThongKeActionPerformed
        // TODO add your handling code here:
        jPanelMQLCP.removeAll();
        jPanelMQLCP.add(new PanelThongKe());
        jPanelMQLCP.repaint();
        jPanelMQLCP.revalidate();
    }//GEN-LAST:event_jButtonThongKeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "-------------CÁC ĐIỀU KHOẢN KHI SỬ DỤNG------------"
            + "\n1. Bạn không bị mất phí sử dụng."
            +"\n2. Bạn có thể tùy chỉnh dữ liệu cá nhân."
            +"\n3. Chúng tôi sẽ mang lại cho bạn môi trường chứng khoán lành mạnh."
            +"\n4. Bạn có thể tổ chức, kết nối, giao dịch chứng khoán thông qua app."
            +"\n5. Chống hành vi có hại cho cộng đồng chúng ta."
            +"\n6. Sử dụng và phát triển, cải thiện dịch vu chúng tô.i"
            +"\n\n Hãy đồng hành cùng chúng tôi", "Điều khoản sử dụng.", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "-------------CÁC CHÍNH SÁCH BẢO MẬT------------"
            + "\n1. Sẽ không để tiết lộ thông tin cá nhân."
            +"\n2. Sẽ không buôn bán tài khoản của bất cứ ai."
            +"\n3. Chúng tôi sẽ ngăn chặn tất cả nguy cơ xâm hại đến dữ liệu."
            +"\n4. Sẽ không tác động đến dữ liệu cá nhân hay tổ chức nào."
            +"\n5. Nghiêm cấm các hành vi giao dịch, mua bán bất hợp pháp."
            +"\n6. Để tâm kỹ càng đến các tài khoản mạo danh."
            +"\n\n Hãy đồng hành cùng chúng tôi", "Chính sách bảo mật.", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Cảm ơn bạn đã phản hồi.");
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bạn hãy gọi 19001020 để được tư vấn miễn phí \n(gặp anh Quokka.)", "Trung tâm trợ giúp", JOptionPane.UNDEFINED_CONDITION);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.add(jPanelTT);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButtonTCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTCMouseEntered
        // TODO add your handling code here:
         jButtonTC.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_jButtonTCMouseEntered

    private void jButtonTCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTCMouseExited
        // TODO add your handling code here:
        jButtonTC.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonTCMouseExited

    private void jButtonQLNDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQLNDTMouseEntered
        // TODO add your handling code here:
         jButtonQLNDT.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_jButtonQLNDTMouseEntered

    private void jButtonQLNDTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQLNDTMouseExited
        // TODO add your handling code here:
        jButtonQLNDT.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonQLNDTMouseExited

    private void jButtonQLCPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQLCPMouseEntered
        // TODO add your handling code here:
         jButtonQLCP.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_jButtonQLCPMouseEntered

    private void jButtonQLCPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQLCPMouseExited
        // TODO add your handling code here:
        jButtonQLCP.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonQLCPMouseExited

    private void jButtonQLGDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQLGDMouseEntered
        // TODO add your handling code here:
        jButtonQLGD.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_jButtonQLGDMouseEntered

    private void jButtonQLGDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQLGDMouseExited
        // TODO add your handling code here:
        jButtonQLGD.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonQLGDMouseExited

    private void jButtonHNXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHNXActionPerformed
        // TODO add your handling code here:
        jPanelMTC.removeAll();
        jPanelMTC.add(new PanelGiaCP("HNX"));
        jPanelMTC.repaint();
        jPanelMTC.revalidate();
    }//GEN-LAST:event_jButtonHNXActionPerformed

    private void jButtonTinTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTinTucActionPerformed
        // TODO add your handling code here:
        jPanelMTC.removeAll();
        jPanelMTC.add(new PanelTinTuc());
        jPanelMTC.repaint();
        jPanelMTC.revalidate();
    }//GEN-LAST:event_jButtonTinTucActionPerformed

    private void jButtonHSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHSXActionPerformed
        // TODO add your handling code here:
        jPanelMTC.removeAll();
        jPanelMTC.add(new PanelGiaCP("HSX"));
        jPanelMTC.repaint();
        jPanelMTC.revalidate();
    }//GEN-LAST:event_jButtonHSXActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           writeFile();
        try {
            ketNoi.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDSLenh;
    private javax.swing.JButton jButtonHNX;
    private javax.swing.JButton jButtonHSX;
    private javax.swing.JButton jButtonLK;
    private javax.swing.JButton jButtonLSGia;
    private javax.swing.JButton jButtonLenhKhop;
    private javax.swing.JButton jButtonLoaiLenh;
    private javax.swing.JButton jButtonNDT;
    private javax.swing.JButton jButtonQLCP;
    private javax.swing.JButton jButtonQLGD;
    private javax.swing.JButton jButtonQLNDT;
    private javax.swing.JButton jButtonSGD;
    private javax.swing.JButton jButtonTC;
    private javax.swing.JButton jButtonTKNH;
    private javax.swing.JButton jButtonTTCP;
    private javax.swing.JButton jButtonThongKe;
    private javax.swing.JButton jButtonTinTuc;
    private javax.swing.JButton jButtonTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanelMQLCP;
    public static javax.swing.JPanel jPanelMQLGD;
    public static javax.swing.JPanel jPanelMQLNDT;
    private javax.swing.JPanel jPanelMTC;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelQLCP;
    private javax.swing.JPanel jPanelQLGD;
    private javax.swing.JPanel jPanelQLNDT;
    private javax.swing.JPanel jPanelTT;
    private javax.swing.JPanel jPanelTrangChu;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
